const jobData = [
  {
    'id': 1,
    'company': 'Photosnap',
    'logo': './images/photosnap.svg',
    'new': true,
    'featured': true,
    'title': 'Senior Frontend Developer',
    'posted': '1d ago',
    'type': 'Full Time',
    'location': 'USA only',
    'role': 'Frontend',
    'level': 'Senior',
    'languages': ['HTML', 'CSS', 'JavaScript']
  },
  {
    'id': 2,
    'company': 'Manage',
    'logo': './images/manage.svg',
    'new': true,
    'featured': true,
    'title': 'Fullstack Developer',
    'posted': '1d ago',
    'type': 'Part Time',
    'location': 'Remote',
    'role': 'Fullstack',
    'level': 'Midweight',
    'languages': ['Python'],
    'tools': ['React']
  },
  {
    'id': 3,
    'company': 'Account',
    'logo': './images/account.svg',
    'new': true,
    'featured': false,
    'title': 'Junior Frontend Developer',
    'posted': '2d ago',
    'type': 'Part Time',
    'location': 'USA only',
    'role': 'Frontend',
    'level': 'Junior',
    'languages': ['JavaScript'],
    'tools': ['React', 'Sass']
  },
  {
    'id': 4,
    'company': 'MyHome',
    'logo': './images/myhome.svg',
    'new': false,
    'featured': false,
    'title': 'Junior Frontend Developer',
    'posted': '5d ago',
    'type': 'contract',
    'location': 'USA only',
    'role': 'Frontend',
    'level': 'Junior',
    'languages': ['JavaScript', 'CSS'],
  },
  {
    'id': 5,
    'company': 'Loop Studios',
    'logo': './images/loop-studios.svg',
    'new': false,
    'featured': false,
    'title': 'Software Engineer',
    'posted': '1w ago',
    'type': 'Full Time',
    'location': 'Worldwide',
    'role': 'Fullstack',
    'level': 'Midweight',
    'languages': ['JavaScript', 'Ruby'],
    'tools': ['Sass']
  },
  {
    'id': 6,
    'company': 'FaceIt',
    'logo': './images/faceit.svg',
    'new': false,
    'featured': false,
    'title': 'Junior Backend Developer',
    'posted': '2w ago',
    'type': 'Full Time',
    'location': 'UK only',
    'role': 'Backend',
    'level': 'Junior',
    'languages': ['Ruby'],
    'tools': ['RoR']
  },
  {
    'id': 7,
    'company': 'Shortly',
    'logo': './images/shortly.svg',
    'new': false,
    'featured': false,
    'title': 'Junior Developer',
    'posted': '2w ago',
    'type': 'Full Time',
    'location': 'Worldwide',
    'role': 'Frontend',
    'level': 'Junior',
    'languages': ['HTML', 'JavaScript'],
    'tools': ['Sass']
  },
  {
    'id': 8,
    'company': 'Insure',
    'logo': './images/insure.svg',
    'new': false,
    'featured': false,
    'title': 'Junior Frontend Developer',
    'posted': '2w ago',
    'type': 'Full Time',
    'location': 'USA only',
    'role': 'Frontend',
    'level': 'Junior',
    'languages': ['JavaScript'],
    'tools': ['Vue', 'Sass']
  },
  {
    'id': 9,
    'company': 'Eyecam Co.',
    'logo': './images/eyecam-co.svg',
    'new': false,
    'featured': false,
    'title': 'Full Stack Engineer',
    'posted': '3w ago',
    'type': 'Full Time',
    'location': 'Worldwide',
    'role': 'Fullstack',
    'level': 'Midweight',
    'languages': ['Python'],
    'tools': ['Django']
  },
  {
    'id': 10,
    'company': 'The Air Filter Company',
    'logo': './images/the-air-filter-company.svg',
    'new': false,
    'featured': false,
    'title': 'Front-end Dev',
    'posted': '1mo ago',
    'type': 'Part Time',
    'location': 'Worldwide',
    'role': 'Frontend',
    'level': 'Junior',
    'languages': ['JavaScript'],
    'tools': ['React', 'Sass']
  }
]
